[mypy]

[mypy-libertai_utils.*]
ignore_missing_imports = True

[mypy-libertai_x402.*]
ignore_missing_imports = True

[mypy-aleph.*]
ignore_missing_imports = True

[mypy-aleph_message.*]
ignore_missing_imports = True

[mypy-paramiko.*]
ignore_missing_imports = True

[mypy-eth_account.*]
ignore_missing_imports = True